In [17]:
from datasets import load_dataset
from sentence_transformers import SentenceTransformer
import psycopg2
from pgvector.psycopg2 import register_vector
import os

ds = load_dataset("lavita/MedQuAD")
data = ds['train']
print(f"# data in MedQuAD: {len(data)}")

# data in MedQuAD: 47441

In [19]:
df = data.to_pandas()

df.head(5)

,document_id,document_source,document_url,category,umls_cui,umls_semantic_types,umls_semantic_group,synonyms,question_id,question_focus,question_type,question,answer
0,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-1,keratoderma with woolly hair,information,What is (are) keratoderma with woolly hair ?,Keratoderma with woolly hair is a group of rel...
1,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-2,keratoderma with woolly hair,frequency,How many people are affected by keratoderma wi...,Keratoderma with woolly hair is rare; its prev...
2,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-3,keratoderma with woolly hair,genetic changes,What are the genetic changes related to kerato...,"Mutations in the JUP, DSP, DSC2, and KANK2 gen..."
3,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-4,keratoderma with woolly hair,inheritance,Is keratoderma with woolly hair inherited ?,Most cases of keratoderma with woolly hair hav...
4,0000559,GHR,https://ghr.nlm.nih.gov/condition/keratoderma-...,None,C0343073,T047,Disorders,KWWH,0000559-5,keratoderma with woolly hair,treatment,What are the treatments for keratoderma with w...,These resources address the diagnosis or manag...

# aaaaaaaaaaaaaaaaaaaaaaaaA

In [65]:
import os
import pandas as pd

def read_json_mimic():
    extracted_data = []

    filepath = "./data_ingestion/data/physionet.org/files/mimic-iii-question-answer/1.0.0/test.final.json"
    with open(filepath, 'r', encoding='utf-8') as file:
        data = pd.read_json(file)
        
    for record in data['data']:
        title = record['title']
        paragraphs = record['paragraphs']
        
        for paragraph in paragraphs:
            context = paragraph.get('context')
            questions = paragraph['qas']
            for question in questions:
                question_text = question['question']
                answers = question['answers']
                for answer in answers:
                    answer_text = answer['text']
                    #print(f"Context: {context}")
                    extracted_data.append({
                        'title': title,
                        'context': context,
                        'question': question_text,
                        'answer': answer_text
                    })
    df = pd.DataFrame(extracted_data)
    return df
df = read_json_mimic()

In [66]:
df.head(4)

,title,context,question,answer
0,177,admission date: [**2124-7-21**] discharge date...,does the patient have a current copd exacerbation,chief complaint: copd exacerbation/shortness o...
1,177,admission date: [**2124-7-21**] discharge date...,does the patient have a history of shortness o...,chief complaint: copd exacerbation/shortness o...
2,177,admission date: [**2124-7-21**] discharge date...,has been the patient ever been considered for ...,chief complaint: copd exacerbation/shortness o...
3,177,admission date: [**2124-7-21**] discharge date...,does the patient have a prior history of short...,chief complaint: copd exacerbation/shortness o...